language : shell

env:
  - PYTHON=3.6

os :
  - linux

cache :
  pip: true

install:
  # pip update
  - pip install --upgrade pip
  - pip install -r req.$PYTHON.txt

script: cd tests && py.test -n auto
