# https://github.com/cclaus/Travis-CI-Python-on-three-OSes/

language : python

os : linux

dist : xenial

python : 
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

# To accelerate
cache :
  pip : true
  directories:
    - $HOME/.cache/pip

before_cache :
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  # pip update
  - pip3 install --upgrade pip
  - pip3 install -r tests/req.$TRAVIS_PYTHON_VERSION.txt

script: cd tests && py.test -n auto
