# https://github.com/cclaus/Travis-CI-Python-on-three-OSes/

language : python

os : linux

dist : xenial

python : 
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

# To accelerate
cache :
  pip : true
  directories:
    - $HOME/.cache/pip

before_cache :
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  # https://phthonhosted.org/CodeChat/.travis.yml.html
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      PYTHON=$TRAVIS_PYTHON_VERSION;
      brew update;
      brew install openssl readline;
      brew outdated pyenv || brew upgrad pyenv;
      brew install pyenv-virtualenv;
      pyenv install $PYTHON;
      export PYENV_VERSION=$PYTHON;
      export PATH="$HOME/.pyenv/shims:${PATH}";
      pyenv-virtualenv venv;
      source venv/bin/activate;
      python --version;
    fi;

install:
  # pip update
  - pip3 install --upgrade pip
  - pip3 install -r tests/req.$TRAVIS_PYTHON_VERSION.txt

script: cd tests && py.test -n auto
