language : shell

matrix:
  include:
    - env: CONDA_PYTHON=3.7.1
      os: osx
    - env: CONDA_PYTHON=3.7.3
      os: linux
    - env: CONDA_PYTHON=3.7.3
      os: osx
    - env: CONDA_PYTHON=2019.07
      os: windows
    - env: CONDA_PYTHON=2019.07
      os: linux
    - env: CONDA_PYTHON=2019.07
      os: osx
    - env: CONDA_PYTHON=nightly
      os: linux
  allow_failures:
    - os: windows
  fast_finish: true

before_cache:
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history $HOME/miniconda/envs/test-environment/conda-meta/history $HOME/miniconda/lib/python3.5/__pycache__ $HOME/miniconda/lib/python3.6/__pycache__ $HOME/miniconda/lib/python3.7/__pycache__;
  - touch $HOME/miniconda/conda-meta/history;

cache :
  pip: true
  directories:
    - $HOME/download
    - $HOME/miniconda

before_install:
  - . tests/before_install_nix_win_cache.sh

install:
  - . tests/install_nix_win_cache.sh

script: py.test -n auto tests/
