# https://github.com/cclaus/Travis-CI-Python-on-three-OSes/

language : python

matrix:
  include:
    - os : linux
      python : 3.6
      env:
        - PYTHON=3.6
    - os : osx
      python : 3.6
      env:
        - PYTHON=3.6
    - os : windows
      language : shell
      env : 
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - PYTHON=3.6
      before_install : choco install python --version 3.6

os :
  - linux

cache :
  pip: true

install:
  # pip update
  - pip3 install --upgrade pip
  - pip3 install -r tests/req.$PYTHON.txt

script: cd tests && py.test -n auto
