name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14, windows-2016]
        anaconda: [2019.07]

    steps:
    - uses: actions/checkout@v1
    - bash: ./.github/workflows/build_env.sh
      displayName: Create Test Environment
      workingDirectory: $(wd)
      env:
        BASHRC: ${{ matrix.bashrc }}
        CONDA_PYTHON: ${{ matrix.anaconda }}
        CONDA_SCRIPT: ${{ matrix.conda_script }}
      
    - bash: ./.github/workflows/run_test.sh
      displayName: pytest
      workingDirectory: $(wd)
      env:
        CONDA_SCRIPT: ${{ matrix.conda_script }}
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      