name: CI (Win)

on: [push]

jobs:
  build:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]
        anaconda: [nightly]

    steps:
    - uses: actions/checkout@v1
    - name: build environment
      env:
        CONDA_PYTHON: ${{ matrix.anaconda }}
      run: bash ./.github/workflows/create_env_test_win.sh
    - name: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/run_test.sh
