name: CI (Win)

on: [push]

jobs:
  build:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]
        conda_script: [Scripts]

        bashrc: [.bash_profile]
        anaconda: [2019.07]

    steps:
    - uses: actions/checkout@v1
    - name: bash_create_env_test_win
      env:
        BASHRC: ${{ matrix.bashrc }}
        CONDA_PYTHON: ${{ matrix.anaconda }}
        CONDA_SCRIPT: ${{ matrix.conda_script }}
      run: bash ./.github/workflows/build_env.sh
    - name: pytest
      env:
        CONDA_SCRIPT: ${{ matrix.conda_script }}
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/run_test.sh
