name: CI (OSX)

on: [push]

jobs:
  build:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14]
        conda_script: [bin]

        bashrc: [.bash_profile]
        anaconda: [3.7.1, 3.7.3, 2019.07, nightly]

    steps:
    - uses: actions/checkout@v1
    - name: bash_create_env_test_posix
      env:
        BASHRC: ${{ matrix.bashrc }}
        CONDA_PYTHON: ${{ matrix.anaconda }}
        CONDA_SCRIPT: ${{ matrix.conda_script }}
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/create_env_test_posix.sh
